<?php

namespace Database\Seeders;

use App\Models\Division;
use App\Models\Section;
use App\Models\User;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $division = Division::where('name', 'Laboratory Services Division')->first();
        $sections = Section::all();

        $getSection = function (string $name) use ($sections) {
            return $sections->firstWhere('name', $name) ?? $sections->first();
        };

        $secAdmin  = $getSection('Office of the Chief / Admin Staff');
        $secLims   = $getSection('LIMS');
        $secChem   = $getSection('Soil Chemistry Section');
        $secRst    = $getSection('Rapid Soil Test Section');
        $secMicro  = $getSection('Soil Microbiology Section');
        $secPhys   = $getSection('Soil Physics Section');
        $secWater  = $getSection('Water Chemistry Section');
        $secTeim   = $getSection('Technical Equipment Instrumentation and Maintenance');

        $divId = $division?->id;

        $users = [
            // ── Admin ─────────────────────────────────────────────────────────
            [
                'first_name' => 'Admin',
                'last_name'  => 'User',
                'name'       => 'Admin User',
                'email'      => 'admin@lims.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secAdmin?->id,
                'status'     => 'ACTIVE',
                'role'       => 'ADMIN',
                'position'   => 'IT Officer III',
            ],
            [
                'first_name' => 'Isaac Vince R.',
                'last_name'  => 'Avila',
                'name'       => 'Isaac Vince R. Avila',
                'email'      => 'isaacvince100@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secLims?->id,
                'status'     => 'ACTIVE',
                'role'       => 'ADMIN',
                'position'   => 'Project Development Officer III',
            ],

            // ── Office of the Chief / Admin Staff ─────────────────────────────
            [
                'first_name' => 'Maribel R.',
                'last_name'  => 'Jalalon',
                'name'       => 'Maribel R. Jalalon',
                'email'      => 'maribel.jalalon@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secAdmin?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Laboratory Chief',
            ],
            [
                'first_name' => 'Ronaldo G.',
                'last_name'  => 'Golpo',
                'name'       => 'Ronaldo G. Golpo',
                'email'      => 'onadgolpo@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secAdmin?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant IV',
            ],

            // ── LIMS (STAFF) ──────────────────────────────────────────────────
            [
                'first_name' => 'John Vincent C.',
                'last_name'  => 'Viojan',
                'name'       => 'John Vincent C. Viojan',
                'email'      => 'jviojan08@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secLims?->id,
                'status'     => 'ACTIVE',
                'role'       => 'STAFF',
                'position'   => 'Project Development Officer III',
            ],
            [
                'first_name' => 'Simon',
                'last_name'  => 'Gabao',
                'name'       => 'Simon Gabao',
                'email'      => 'simongabao1925@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secLims?->id,
                'status'     => 'ACTIVE',
                'role'       => 'STAFF',
                'position'   => 'Computer Programmer II',
            ],
            [
                'first_name' => 'Jareen A.',
                'last_name'  => 'Marquez',
                'name'       => 'Jareen A. Marquez',
                'email'      => 'marquez.jareen@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secLims?->id,
                'status'     => 'ACTIVE',
                'role'       => 'STAFF',
                'position'   => 'Computer Programmer II',
            ],
            [
                'first_name' => 'John Carlo V.',
                'last_name'  => 'Go Lim Tai',
                'name'       => 'John Carlo V. Go Lim Tai',
                'email'      => 'jgolimtai072216@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secLims?->id,
                'status'     => 'ACTIVE',
                'role'       => 'STAFF',
                'position'   => 'Information Systems Analyst I',
            ],
            [
                'first_name' => 'Adrian Jake L.',
                'last_name'  => 'Licayan',
                'name'       => 'Adrian Jake L. Licayan',
                'email'      => 'licayan.adrianjake.libres@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secLims?->id,
                'status'     => 'ACTIVE',
                'role'       => 'STAFF',
                'position'   => 'Project Development Officer I',
            ],

            // ── Soil Chemistry Section ────────────────────────────────────────
            [
                'first_name' => 'Florfina P.',
                'last_name'  => 'Sanchez',
                'name'       => 'Florfina P. Sanchez',
                'email'      => 'florfina.sanchez@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist IV',
            ],
            [
                'first_name' => 'Ezra Mae B.',
                'last_name'  => 'Gamboa',
                'name'       => 'Ezra Mae B. Gamboa',
                'email'      => 'ezra.gamboa@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Evelyn C.',
                'last_name'  => 'Ramos',
                'name'       => 'Evelyn C. Ramos',
                'email'      => 'evelyn.ramos@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Johanna Lindsay G.',
                'last_name'  => 'Lautchang',
                'name'       => 'Johanna Lindsay G. Lautchang',
                'email'      => 'jglautchang@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist III',
            ],
            [
                'first_name' => 'Kyle Angelo H.',
                'last_name'  => 'Macaslang',
                'name'       => 'Kyle Angelo H. Macaslang',
                'email'      => 'kyleangeloherrera@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Xena S.',
                'last_name'  => 'De Tomas',
                'name'       => 'Xena S. De Tomas',
                'email'      => 'detomasxena@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Nicole A.',
                'last_name'  => 'Caragay',
                'name'       => 'Nicole A. Caragay',
                'email'      => 'caragaynicole@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Jenalyn D.',
                'last_name'  => 'Osuna',
                'name'       => 'Jenalyn D. Osuna',
                'email'      => 'jdosuna.rch@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Neil Ivan C.',
                'last_name'  => 'Baribe',
                'name'       => 'Neil Ivan C. Baribe',
                'email'      => 'baribeneilivan@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Project Development Officer II',
            ],
            [
                'first_name' => 'Mauro C.',
                'last_name'  => 'Miano Jr.',
                'name'       => 'Mauro C. Miano Jr.',
                'email'      => 'mimaumianojra1plus@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Romeo B.',
                'last_name'  => 'Vargas Jr.',
                'name'       => 'Romeo B. Vargas Jr.',
                'email'      => 'romeovargas0806@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Rhea Faye',
                'last_name'  => 'Paulino',
                'name'       => 'Rhea Faye Paulino',
                'email'      => 'rheafayepaulinox@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Aljun G.',
                'last_name'  => 'Tusi',
                'name'       => 'Aljun G. Tusi',
                'email'      => 'aljuntusi@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Julianne Kate A.',
                'last_name'  => 'Gutierrez',
                'name'       => 'Julianne Kate A. Gutierrez',
                'email'      => 'juliannekateo@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist I',
            ],
            [
                'first_name' => 'Marivic B.',
                'last_name'  => 'Limos',
                'name'       => 'Marivic B. Limos',
                'email'      => 'marius121806@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant III',
            ],
            [
                'first_name' => 'Melvin B.',
                'last_name'  => 'Arvizo',
                'name'       => 'Melvin B. Arvizo',
                'email'      => 'arvizomelvin69@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant III',
            ],
            [
                'first_name' => 'Catherine C.',
                'last_name'  => 'Aggasid',
                'name'       => 'Catherine C. Aggasid',
                'email'      => 'cathcafirmaaggasid@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secChem?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant III',
            ],

            // ── Rapid Soil Test Section ───────────────────────────────────────
            [
                'first_name' => 'Shirley S.',
                'last_name'  => 'Buduan',
                'name'       => 'Shirley S. Buduan',
                'email'      => 'shirley.buduan@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist IV',
            ],
            [
                'first_name' => 'Marjorie Jean E.',
                'last_name'  => 'Tao',
                'name'       => 'Marjorie Jean E. Tao',
                'email'      => 'marjorie.tao@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Engr. Hazel Jane M.',
                'last_name'  => 'Faa',
                'name'       => 'Engr. Hazel Jane M. Faa',
                'email'      => 'hazel.faa@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Mary Joy Niegos',
                'last_name'  => 'Gumangan',
                'name'       => 'Mary Joy Niegos Gumangan',
                'email'      => 'maryjoy.gumangan99@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Keyfej Calimlim',
                'last_name'  => 'Ramos',
                'name'       => 'Keyfej Calimlim Ramos',
                'email'      => 'kayeramos0830@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist I',
            ],
            [
                'first_name' => 'Jose Pepito A.',
                'last_name'  => 'Espinili',
                'name'       => 'Jose Pepito A. Espinili',
                'email'      => 'josepepito.espinili@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Laboratory Technician II',
            ],
            [
                'first_name' => 'Elisha Jean Cañeza',
                'last_name'  => 'Somosa',
                'name'       => 'Elisha Jean Cañeza Somosa',
                'email'      => 'somosaelishajean@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Project Development Officer II',
            ],
            [
                'first_name' => 'Christine Joy Graza',
                'last_name'  => 'Lasola',
                'name'       => 'Christine Joy Graza Lasola',
                'email'      => 'cjlasola@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Elijah S.',
                'last_name'  => 'Canlas',
                'name'       => 'Elijah S. Canlas',
                'email'      => 'canlaselijahs@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Anito M.',
                'last_name'  => 'Tisado Jr.',
                'name'       => 'Anito M. Tisado Jr.',
                'email'      => 'tisadoanito@gmai.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Christlle Bhrey P.',
                'last_name'  => 'Dedal',
                'name'       => 'Christlle Bhrey P. Dedal',
                'email'      => 'cbpdedal@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant III',
            ],
            [
                'first_name' => 'Hosea Neil O.',
                'last_name'  => 'Dulay',
                'name'       => 'Hosea Neil O. Dulay',
                'email'      => 'hosea.neil.16@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secRst?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant I',
            ],

            // ── Soil Microbiology Section ─────────────────────────────────────
            [
                'first_name' => 'Jamie Ann B.',
                'last_name'  => 'Tumolva',
                'name'       => 'Jamie Ann B. Tumolva',
                'email'      => 'jamie.tumolva@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Supervising Agriculturist',
            ],
            [
                'first_name' => 'Shaira Mhel Joy Melendrez',
                'last_name'  => 'Granada',
                'name'       => 'Shaira Mhel Joy Melendrez Granada',
                'email'      => 'shaira.granada@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Shaun Adrian P.',
                'last_name'  => 'Villadiego',
                'name'       => 'Shaun Adrian P. Villadiego',
                'email'      => 'shaun.villadiego@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Chari Ann A.',
                'last_name'  => 'Maestre',
                'name'       => 'Chari Ann A. Maestre',
                'email'      => 'chari.maestre@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Valerie Joy A.',
                'last_name'  => 'Valdez',
                'name'       => 'Valerie Joy A. Valdez',
                'email'      => 'valerie021492@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Project Assistant IV',
            ],
            [
                'first_name' => 'Jamie Decibel L.',
                'last_name'  => 'Emiterio',
                'name'       => 'Jamie Decibel L. Emiterio',
                'email'      => 'jamiedecibel@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Ariel R.',
                'last_name'  => 'Lumilay Jr.',
                'name'       => 'Ariel R. Lumilay Jr.',
                'email'      => 'alumilayjr@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Neil Philip N.',
                'last_name'  => 'Sta. Rosa',
                'name'       => 'Neil Philip N. Sta. Rosa',
                'email'      => 'neil.philip.starosa@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Leara Faye F.',
                'last_name'  => 'Varquez',
                'name'       => 'Leara Faye F. Varquez',
                'email'      => 'lffvarquez.bswm@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Joshua Carlo T.',
                'last_name'  => 'Cuyco',
                'name'       => 'Joshua Carlo T. Cuyco',
                'email'      => 'joshuacarlocuyco14@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Analyst',
            ],
            [
                'first_name' => 'Christopher Tambao',
                'last_name'  => 'Roque',
                'name'       => 'Christopher Tambao Roque',
                'email'      => 'christopher112787@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Analyst',
            ],
            [
                'first_name' => 'Tracy Clara S.',
                'last_name'  => 'Almario',
                'name'       => 'Tracy Clara S. Almario',
                'email'      => 'tracyclara.almario123102@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secMicro?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Administrative Assistant I',
            ],

            // ── Soil Physics Section ──────────────────────────────────────────
            [
                'first_name' => 'Agnes C.',
                'last_name'  => 'Morada',
                'name'       => 'Agnes C. Morada',
                'email'      => 'agnes.morada@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Supervising Agriculturist',
            ],
            [
                'first_name' => 'Wilfredo O.',
                'last_name'  => 'De Mesa Jr.',
                'name'       => 'Wilfredo O. De Mesa Jr.',
                'email'      => 'wilfred.demesa@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Senior Agriculturist',
            ],
            [
                'first_name' => 'Romeo C.',
                'last_name'  => 'Arocena Jr.',
                'name'       => 'Romeo C. Arocena Jr.',
                'email'      => 'lic.rcarocenajr@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist I',
            ],
            [
                'first_name' => 'Christian Paul O.',
                'last_name'  => 'Baniqued',
                'name'       => 'Christian Paul O. Baniqued',
                'email'      => 'cpbaniqued11036@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Agriculturist II',
            ],
            [
                'first_name' => 'Bobby James R.',
                'last_name'  => 'Brion',
                'name'       => 'Bobby James R. Brion',
                'email'      => 'brionbobbyjames@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Jomari M.',
                'last_name'  => 'Ligsay',
                'name'       => 'Jomari M. Ligsay',
                'email'      => 'ligsayjomari@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Exequiel T.',
                'last_name'  => 'Corcelles',
                'name'       => 'Exequiel T. Corcelles',
                'email'      => 'quielkiel1358@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secPhys?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Aide',
            ],

            // ── Water Chemistry Section ───────────────────────────────────────
            [
                'first_name' => 'Joshua Mikhel B.',
                'last_name'  => 'Reyes',
                'name'       => 'Joshua Mikhel B. Reyes',
                'email'      => 'joshua.reyes@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist III',
            ],
            [
                'first_name' => 'Mary Claire Alyssa E.',
                'last_name'  => 'Pras',
                'name'       => 'Mary Claire Alyssa E. Pras',
                'email'      => 'maryclaire.pras@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Arthur V.',
                'last_name'  => 'Baraoidan',
                'name'       => 'Arthur V. Baraoidan',
                'email'      => 'arthur.baraoidan@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Laboratory Technician II',
            ],
            [
                'first_name' => 'Faye Arielli C.',
                'last_name'  => 'Butaran',
                'name'       => 'Faye Arielli C. Butaran',
                'email'      => 'faye.butaran@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist III',
            ],
            [
                'first_name' => 'Mikaella',
                'last_name'  => 'Ibis',
                'name'       => 'Mikaella Ibis',
                'email'      => 'ibismika30@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist II',
            ],
            [
                'first_name' => 'Sherlyn D.',
                'last_name'  => 'Parido',
                'name'       => 'Sherlyn D. Parido',
                'email'      => 'spjp3123@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Specialist I',
            ],
            [
                'first_name' => 'Christian Mae B.',
                'last_name'  => 'Moncada',
                'name'       => 'Christian Mae B. Moncada',
                'email'      => 'moncadamae@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Analyst',
            ],
            [
                'first_name' => 'Ezra D.',
                'last_name'  => 'Almazan',
                'name'       => 'Ezra D. Almazan',
                'email'      => 'ezra.doble.almazan@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secWater?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Analyst',
            ],

            // ── Technical Equipment Instrumentation and Maintenance ───────────
            [
                'first_name' => 'Bergil G.',
                'last_name'  => 'Bernaldo',
                'name'       => 'Bergil G. Bernaldo',
                'email'      => 'bergil.bernaldo@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Chemist III',
            ],
            [
                'first_name' => 'Joseph B.',
                'last_name'  => 'Malapitan',
                'name'       => 'Joseph B. Malapitan',
                'email'      => 'joseph.malapitan@bswm.da.gov.ph',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Laboratory Technician II',
            ],
            [
                'first_name' => 'Ryan P.',
                'last_name'  => 'Sanchez',
                'name'       => 'Ryan P. Sanchez',
                'email'      => 'ryan.slash.sanchez@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Laboratory Technician I',
            ],
            [
                'first_name' => 'Christopher D.',
                'last_name'  => 'Edaugal',
                'name'       => 'Christopher D. Edaugal',
                'email'      => 'chrisedaugal@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Engineer III',
            ],
            [
                'first_name' => 'Alexander T.',
                'last_name'  => 'Areta',
                'name'       => 'Alexander T. Areta',
                'email'      => 'alexanderareta.teim@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Engineer II',
            ],
            [
                'first_name' => 'Louie C.',
                'last_name'  => 'Sablay',
                'name'       => 'Louie C. Sablay',
                'email'      => 'sablaylouie826@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Engineer II',
            ],
            [
                'first_name' => 'Jerome Keith S.',
                'last_name'  => 'Pascual',
                'name'       => 'Jerome Keith S. Pascual',
                'email'      => 'j.pascual1769@gmail.com',
                'password'   => 'password',
                'division_id' => $divId,
                'section_id' => $secTeim?->id,
                'status'     => 'ACTIVE',
                'role'       => 'USER',
                'position'   => 'Science Research Analyst',
            ],
        ];

        $seededEmails = [];
        foreach ($users as $userData) {
            User::updateOrCreate(
                ['email' => $userData['email']],
                $userData
            );
            $seededEmails[] = $userData['email'];
        }

        User::whereNotIn('email', $seededEmails)->delete();
    }
}
